/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.CardLayout;

/**
 *
 * @author Denny Hermawan
 */
public class FPenampilGambarButton extends javax.swing.JFrame {

    /**
     * Creates new form FUtama
     */
    public FPenampilGambarButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BPanel = new javax.swing.JPanel();
        BAlgo = new javax.swing.JButton();
        BWeb = new javax.swing.JButton();
        BPhyton = new javax.swing.JButton();
        BExit = new javax.swing.JButton();
        IPanel = new javax.swing.JPanel();
        LAlgo = new javax.swing.JLabel();
        LWeb = new javax.swing.JLabel();
        LPhyton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BAlgo.setText("ALGO");
        BAlgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAlgoActionPerformed(evt);
            }
        });
        BPanel.add(BAlgo);

        BWeb.setText("WEB");
        BWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BWebActionPerformed(evt);
            }
        });
        BPanel.add(BWeb);

        BPhyton.setText("PHYTON");
        BPhyton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPhytonActionPerformed(evt);
            }
        });
        BPanel.add(BPhyton);

        BExit.setText("EXIT");
        BExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExitActionPerformed(evt);
            }
        });
        BPanel.add(BExit);

        getContentPane().add(BPanel, java.awt.BorderLayout.PAGE_START);

        IPanel.setLayout(new java.awt.CardLayout());

        LAlgo.setIcon(new javax.swing.ImageIcon("E:\\SEMESTER 5\\PBO 2\\Pertemuan 9\\ALGO.jpg")); // NOI18N
        IPanel.add(LAlgo, "0");
        LAlgo.getAccessibleContext().setAccessibleName("0");

        LWeb.setIcon(new javax.swing.ImageIcon("E:\\SEMESTER 5\\PBO 2\\Pertemuan 9\\WEB.jpg")); // NOI18N
        IPanel.add(LWeb, "1");
        LWeb.getAccessibleContext().setAccessibleName("1");

        LPhyton.setIcon(new javax.swing.ImageIcon("E:\\SEMESTER 5\\PBO 2\\Pertemuan 9\\PHYTON.jpg")); // NOI18N
        IPanel.add(LPhyton, "2");
        LPhyton.getAccessibleContext().setAccessibleName("2");

        getContentPane().add(IPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAlgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAlgoActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (IPanel.getLayout());
        cl.show(IPanel, "0");
    }//GEN-LAST:event_BAlgoActionPerformed

    private void BWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BWebActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (IPanel.getLayout());
        cl.show(IPanel, "1");
    }//GEN-LAST:event_BWebActionPerformed

    private void BPhytonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPhytonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (IPanel.getLayout());
        cl.show(IPanel, "2");
    }//GEN-LAST:event_BPhytonActionPerformed

    private void BExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPenampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPenampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPenampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPenampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPenampilGambarButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAlgo;
    private javax.swing.JButton BExit;
    private javax.swing.JPanel BPanel;
    private javax.swing.JButton BPhyton;
    private javax.swing.JButton BWeb;
    private javax.swing.JPanel IPanel;
    private javax.swing.JLabel LAlgo;
    private javax.swing.JLabel LPhyton;
    private javax.swing.JLabel LWeb;
    // End of variables declaration//GEN-END:variables
}
