/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.CardLayout;

/**
 *
 * @author Denny Hermawan
 */
public class FPenampilGambarComboBox extends javax.swing.JFrame {

    /**
     * Creates new form FPenampilGambarComboBox
     */
    public FPenampilGambarComboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        IPanel = new javax.swing.JPanel();
        LAlgo = new javax.swing.JLabel();
        LWeb = new javax.swing.JLabel();
        LPhyton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pilih Gambar: ");
        BPanel.add(jLabel1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALGO", "WEB", "PHYTON" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        BPanel.add(jComboBox1);

        getContentPane().add(BPanel, java.awt.BorderLayout.PAGE_START);

        IPanel.setLayout(new java.awt.CardLayout());

        LAlgo.setIcon(new javax.swing.ImageIcon("E:\\SEMESTER 5\\PBO 2\\Pertemuan 9\\ALGO.jpg")); // NOI18N
        IPanel.add(LAlgo, "0");
        LAlgo.getAccessibleContext().setAccessibleName("0");

        LWeb.setIcon(new javax.swing.ImageIcon("E:\\SEMESTER 5\\PBO 2\\Pertemuan 9\\WEB.jpg")); // NOI18N
        IPanel.add(LWeb, "1");
        LWeb.getAccessibleContext().setAccessibleName("1");

        LPhyton.setIcon(new javax.swing.ImageIcon("E:\\SEMESTER 5\\PBO 2\\Pertemuan 9\\PHYTON.jpg")); // NOI18N
        IPanel.add(LPhyton, "2");
        LPhyton.getAccessibleContext().setAccessibleName("2");

        getContentPane().add(IPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (IPanel.getLayout());
        cl.show (IPanel, String.valueOf(jComboBox1.getSelectedIndex()));
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPenampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPenampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPenampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPenampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPenampilGambarComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BPanel;
    private javax.swing.JPanel IPanel;
    private javax.swing.JLabel LAlgo;
    private javax.swing.JLabel LPhyton;
    private javax.swing.JLabel LWeb;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
